name: Build
on:
  push:
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make install
      - run: make ci.lint
      - run: make ci.test
      - run: make ci.build
