name: Check
on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node with cache
        uses: actions/setup-node@v2
        with: { node-version: "14", cache: "yarn" }
      - name: Install Yarn packages
        run: yarn install --frozen-lockfile
      - run: yarn build
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Node with cache
        uses: actions/setup-node@v2
        with: { node-version: "14", cache: "yarn" }
      - name: Install Yarn packages
        run: yarn install --frozen-lockfile
      - name: Check prettier
        run: |
          yarn run prettier
          CODE=$?
          if [ "$CODE" != "0"  ]; then exit 1; fi
