name: Deployment
on:
  push:
    branches: [master, development]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - name: Build react
        run: |
          OWNER=$(echo "${GITHUB_REPOSITORY}" | sed --expression 's/\/.*//g')
          REPO=$(echo "${GITHUB_REPOSITORY}" | sed --expression 's/.*\///g')
          export PUBLIC_URL="https://${OWNER}.github.io/${REPO}/"
          yarn build
      - name: Publish
        uses: rdok/publish-gh-page-action@v1.1.0
        with:
          directory: build
          github-actor: ${{ github.actor }}
          github-token: ${{ github.token }}
          github-repository: ${{ github.repository }}
