name: Deployment
on:
  push:
    branches: 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - name: Build app
        run: |
          OWNER=$(echo "${GITHUB_REPOSITORY}" | sed --expression 's/\/.*//g')
          REPO=$(echo "${GITHUB_REPOSITORY}" | sed --expression 's/.*\///g')
          export PUBLIC_URL="https://${OWNER}.github.io/${REPO}/"
          yarn build
      - name: Publish app
        uses: rdok/publish-gh-page-action@v1.2.2
        with:
          directory: build
